@pingurus [QMS-314] Fix/Add POI categories (Resolve POIs to garmin symbols)
Maproom/qmapshack pull request #335
Opened 2021-02-22 10:59 UTC by pingurus

_**Note: Do not delete any of the sections Answer them all. Replace the descriptive text by your answer**_

**What is the linked issue for this pull request (start with a `#`):**

QMS-#314

**Describe roughly what you have done:**

I added that the POIs when copied over to a project now get a symbol that match their type, if available.

**What steps have to be done to perform a simple smoke test:**

1. Open a *.poi file
2. Copy POIs over to a project via right-click or 'Select Items On Map'
3. See that you are asked if there is no symbol to choose one.

**Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):**

- [x] yes

**Is every user facing string in a tr() macro?**

- [x] yes

**Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.**

- [x] yes, I didn't forget to change changelog.txt

2021-02-22 15:24 UTC, wthaem commented
*Do you want to set the symbol for each POI that has no automatically assigned symbol seperately?:*

* spelling: seperately ===> separately
* meaning of the text is not quite clear. Does it mean:

    *Press "Yes" if you want to choose an icon for each new waypoint. Press "No" if you want to assign automatically the last used waypoint icon.


*Context menu `Add ... POI ...`:*

There are now 2 types of POIs: those from a vector map and those from a POI file. Both may have the same OSM source and thus, the same name and location. In such a case, the context menu shows 2 more or less equal menu entries. Both producing the same waypoint in the workspace. Is it possible to suppress one of these menu entries? 

A similar situation occurs in clusters of POIs (e.g. emergency telephones on a motorway - there are typically 2 of them on both sides of the motorway, i.e. they are quite often in a cluster): the context menu shows 2 or even more equal entries, each one creating a different waypoint - looks ugly.

2021-02-22 15:50 UTC, pingurus commented
> There are now 2 types of POIs: those from a vector map and those from a POI file. Both may have the same OSM source and thus, the same name and location. In such a case, the context menu shows 2 more or less equal menu entries. Both producing the same waypoint in the workspace. Is it possible to suppress one of these menu entries?
>
>A similar situation occurs in clusters of POIs (e.g. emergency telephones on a motorway - there are typically 2 of them on both sides of the motorway, i.e. they are quite often in a cluster): the context menu shows 2 or even more equal entries, each one creating a different waypoint - looks ugly.

I'll try to implement something over at #330. Detecting duplicates from vector maps or different poi file sources almost certainly won't work though.

2021-02-22 15:56 UTC, pingurus commented
@wthaem What do you think of the text now? 
Should I be more 'aggressive' in assigning icons, i.e. mapping bicycle parkings to the general parking icon? There might be some cases where I missed a good mapping.

2021-02-23 08:10 UTC, wthaem commented
>What do you think of the text now?

Use this text.

>Should I be more 'aggressive' in assigning icons, i.e. mapping bicycle parkings to the general parking icon? 

No.

2021-03-13 15:38 UTC, pingurus commented
@kiozen this one is also ready for review, I'm not sure if you received a notification :smile:

2021-03-15 09:28 UTC, kiozen requested changes

2021-03-15 09:28 UTC, kiozen commented on src/qmapshack/gis/wpt/CGisItemWpt.cpp
Let's clean this up a bit:

```
void CGisItemWpt::newWpt(const QPointF& pt, const QString &name, const QString &desc, IGisProject * project, const QString& icon, bool openEditWIndow)
{
    SETTINGS;    
    const QString& _icon = icon.isEmpty() ? cfg.value("Waypoint/lastIcon", "Waypoint").toString() : icon;
    const QString& _name = name.isEmpty() ? getLastName("") : name;

    CGisItemWpt * wpt = new CGisItemWpt(pt, _name, _icon, project);
```

2021-03-16 09:12 UTC, kiozen commented
@pingurus can you please do a quick rebase?

2021-03-16 19:34 UTC, pingurus commented
@kiozen rebase done.

2021-03-17 07:15 UTC, kiozen requested changes

2021-03-17 07:15 UTC, kiozen commented on src/qmapshack/gis/wpt/CGisItemWpt.cpp
> +void CGisItemWpt::newWpt(const QPointF& pt, const QString &name, const QString &desc, IGisProject * project, QString icon, bool openEditWIndow)
`const QString& icon`

2021-03-18 16:34 UTC, kiozen commented on src/qmapshack/gis/wpt/CGisItemWpt.cpp
> +void CGisItemWpt::newWpt(const QPointF& pt, const QString &name, const QString &desc, IGisProject * project, QString icon, bool openEditWIndow)
Ping! If you fix this I can press the :radio_button: 

.... else I merge PR #346 and you have to rebase again :fire:

2021-03-18 18:05 UTC, merged