[QMS-307] Optimization of POI query
Maproom/qmapshack pull request #339
Opened 2021-03-13 15:30 UTC by pingurus

_**Note: Do not delete any of the sections Answer them all. Replace the descriptive text by your answer**_

**What is the linked issue for this pull request (start with a `#`):**

QMS-#307

**Describe roughly what you have done:**

I added checking for bounding box when fetching POIs.

Loading all categories at once (instead of querying the same area multiple times) would take some effort to do in a sensible way and at least on my machine it works relatively smoothly now as long as it is not zoomed out too far.

**What steps have to be done to perform a simple smoke test:**

1. Activate POI file
2. Move outside bounding box of loaded file
3. See that loading does not take any time (before it did)

**Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):**

- [x] yes

**Is every user facing string in a tr() macro?**

- [x] yes

**Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.**

- [x] yes, I didn't forget to change changelog.txt

2021-03-20 11:24 UTC, kiozen commented
@pingurus  We need a rebase to go on.

2021-03-20 15:28 UTC, pingurus commented
done :smile:

2021-03-20 16:06 UTC, pingurus commented
feature/pois fails to compile for me.

```
In file included from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/canvas/CCanvas.cpp:51:
/home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/poi/CPoiDraw.h:38:10: error: conflicting return type specified for ‘virtual void CPoiDraw::setProjection(const QString&)’
   38 |     void setProjection(const QString& proj) override;
      |          ^~~~~~~~~~~~~
In file included from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/dem/CDemDraw.h:22,
                 from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/canvas/CCanvas.cpp:23:
/home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/canvas/IDrawContext.h:142:18: note: overridden function is ‘virtual bool IDrawContext::setProjection(const QString&)’
  142 |     virtual bool setProjection(const QString& projStr);
      |                  ^~~~~~~~~~~~~
In file included from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/CMainWindow.cpp:52:
/home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/poi/CPoiDraw.h:38:10: error: conflicting return type specified for ‘virtual void CPoiDraw::setProjection(const QString&)’
   38 |     void setProjection(const QString& proj) override;
      |          ^~~~~~~~~~~~~
In file included from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/dem/CDemDraw.h:22,
                 from /home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/CMainWindow.cpp:24:
/home/x002a/Documents/Outdoor/QMS_dev/QMapShack/src/qmapshack/canvas/IDrawContext.h:142:18: note: overridden function is ‘virtual bool IDrawContext::setProjection(const QString&)’
  142 |     virtual bool setProjection(const QString& projStr);
      |                  ^~~~~~~~~~~~~
make[2]: *** [src/qmapshack/CMakeFiles/qmapshack.dir/build.make:1861: src/qmapshack/CMakeFiles/qmapshack.dir/canvas/CCanvas.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/qmapshack/CMakeFiles/qmapshack.dir/build.make:1835: src/qmapshack/CMakeFiles/qmapshack.dir/CMainWindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:237: src/qmapshack/CMakeFiles/qmapshack.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

Should I fix it here or in a separate PR?

2021-03-20 17:04 UTC, kiozen commented
fix it with a quick PR

2021-03-21 08:52 UTC, kiozen requested changes
You might consider my comment. Up to you. Let me know and I push the button.

2021-03-21 08:52 UTC, kiozen commented on src/qmapshack/poi/CPoiPOI.cpp
> +
Just a matter of taste but imho this is easier to read:

```
void CPoiPOI::loadPOIsFromFile(quint64 categoryID, qreal minLonM10, qreal minLatM10)
{
    // check if query is within bounds
    if(bbox.intersects({minLonM10 / 10, minLatM10 / 10, 1.0 / 10, 1.0 / 10}))
    {
        return;
    }
```

2021-03-21 09:01 UTC, pingurus commented
You forgot a `!`, but it is indeed much better to read :laughing:

2021-03-21 09:17 UTC, kiozen commented
> You forgot a `!`, but it is indeed much better to read laughing

oops :blush:

2021-03-21 09:18 UTC, merged