[QM-476] Added the coloring by elevation
Maproom/qmapshack pull request #477
Opened 2022-01-21 20:49 UTC by slammyV

Added functionality in the DEM to color the map by the elevation
values including a switchable coresponding color scale legend and
min/max elevation spinners in the DEM property dialog.
Modified the scroll setting in the DEM list to allow for proper
scrolling of the DEM property tree widget.

### What is the linked issue for this pull request:
[comment]: # (Add the ticket number behind QMS-# )

QMS-#

### What you have done:
[comment]: # (Describe roughly.)

### Steps to perform a simple smoke test:
[comment]: # (List the steps.)

1. Open whatever
2. Click here

### Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):

- [ ] yes

### Is every user facing string in a tr() macro?

- [ ] yes

### Did you add the ticket number and title into the changelog? Keep the numeric order in each release block.

- [ ] yes, I didn't forget to change changelog.txt

2022-01-21 21:05 UTC, slammyV commented
It is my first contribution. Hopefully I forgot nothing...

2022-01-22 13:04 UTC, kiozen requested changes
Well done. Just minor nitpicking.

2022-01-22 13:04 UTC, kiozen commented on src/qmapshack/dem/CDemVRT.cpp
> +        if(doElevationShading())
make it a method please. This is already too much spaghetti code without these additional lines.

2022-01-22 19:01 UTC, slammyV reviewed
Hopefully now it is ok. Thankx for the comments.

2022-01-23 22:44 UTC, mitxel-m commented
Thanks for this new feature, very useful. 

 Tested and working for me. 

Screenshot:

![](https://i.ibb.co/rGYc2kS/Selecci-n-052.png)

screenshot with more detail, limits from 1000 to 1400, the colours match the contour lines. (DEM pixel is 5x5m)

![](https://i.ibb.co/kg9P4y0/Selecci-n-053.png)

The only thing I can suggest is about the legend, which now looks like this:

![](https://i.ibb.co/0s1Q1QM/Selecci-n-051.png)

and I think it would be more intuitive the opposite, I mean the lowest value and the blue colour at the bottom, and the highest value and the red colour at the top . ( ... if possible)   

:-)

2022-01-24 06:43 UTC, kiozen commented
@slammyV Do you want to change the legend? Else I would press the button. ()If you change it use more const references in the legend code to avoid copies of QColor on the stack.)

2022-01-24 07:01 UTC, slammyV commented
@kiozen I will change this.

2022-01-24 12:14 UTC, slammyV commented
Swapped the legend upside down.
Made the color in the legend const.

2022-01-24 12:57 UTC, merged

2022-01-24 12:58 UTC, kiozen commented
Thanks!